# NOTE: A Makefile consists of rules, where each rule has a target, zero or
# 		more dependencies, and zero or more commands. Here, "a.out" is the
# 		target and "hello.c" is its dependency. If "a.out" doesn't exist, or if
# 		it is older than "hello.c", then the command "gcc ..." will be run.
a.out: hello.c
	gcc -Wall -Wextra -Werror -ansi -pedantic hello.c
